### ISSUE TITLE
Problem facing with process.system and build.make

### ISSUE THREAD

**Issue by santhosh93** [avocado-framework/avocado-misc-tests#133] opened 2016-08-09 15:47 UTC
Currently, I am working on adding a test case which git clones glibc suite and does make and make check . Below is the coding done:

  git.get_repo('git://sourceware.org/git/glibc.git', destination_dir=self.srcdir)
        os.chdir(self.build_dir)
        process.system(self.srcdir + '/configure --prefix=%s' % self.build_dir)
        build.make(self.build_dir, extra_args='-j %d' % multiprocessing.cpu_count())
    def test(self):
        build.make(self.build_dir, extra_args='check -j %d' %
                   multiprocessing.cpu_count())

The test is getting hanged at the last without getting terminated and it lasts long there only
the same problem exists even if process.system is used in the place of build.make

But it works fine with os.system

**Comment by PraveenPenguin** [comment] 2016-09-14 16:57
@apahim  @ldoktor can you please have a look it to this issue ?

Regards
Praveen

**Comment by lmr** [comment] 2016-09-14 17:46
I haven't looked at it yet, but hangs usually mean the program blocks waiting for user input.

Let me see if I can reproduce this.

**Comment by lmr** [comment] 2016-09-14 18:00
I found the problem. The author is using `sudo=True`, which is prompting a password.

I'm not even sure why he wanted to use `sudo=True` here. If you are planning on using that, you must run under a user that has the rights to do it without prompting password (requires a proper sudo configuration).

**Comment by lmr** [comment] 2016-09-14 18:17
Closing #133, since all the author has to do is to remove `sudo=True` from his call to `process.system`.

**Comment by lmr** [comment] 2016-09-14 19:28
OK, apparently 'make check' is not completing. I'll reopen this and keep investigating.

**Comment by PraveenPenguin** [comment] 2016-09-22 16:55
@lmr have you any luck on this issue ?

**Comment by lmr** [comment] 2016-09-22 18:56
@PraveenPenguin not yet. I've recently arrived from an almost 30 day travel, so I've been busy tending to daily life errands. Hopefully I'll get back to it next week.

From my initial investigation, `make check` in the context of the test triggers a deadlock in process.run code. I wasn't able to pinpoint what makes this command so special, since I have to pack and travel.

**Comment by PraveenPenguin** [comment] 2016-09-23 03:50
@lmr sure Thanks a lot for looking in to this !!

**Comment by ldoktor** [comment] 2016-09-23 17:07
I tired that with the `sudo=False` and I'm unable to reproduce it when running as user, nor as root. I also tried 8 cores and 1 cores (via taskset).

To make sure it's not avocado's process I tried:

``` python
from avocado.utils import process
a=process.run("seq 1 99999999 | xargs", shell=True)
a=process.run("dd if=/dev/zero bs=1G count=1")
a=process.run("while [ -e /tmp/a ]; do echo dfnaskjfndskfnasjkfnadf; done", shell=True)
a=process.run("dd if=/dev/zero bs=1G count=3")
a=process.run("dd if=/dev/zero bs=1 count=100M")
```

which should simulate various stresses and it also worked well. Are you sure this issue is related to avocado and not the Glibc check? How often does this happen and what is the target system?

**Comment by ldoktor** [comment] 2016-09-23 17:08
^^ also what avocado version do you run, I'm using the current master.

**Comment by lmr** [comment] 2016-09-23 21:07
@ldoktor the problem is specific with that make check, it really deadlocks.
When I tried calling process.run from ipython it didn't deadlock for some
reason.

**Comment by ldoktor** [comment] 2016-09-26 11:10
@lmr can you please share your specs (no cpus, python version, os version, glibc/test versions, ...) as well as the information about the fail-rate? I was not able to reproduce it at all after several trials on F23.

**Comment by santhosh93** [comment] 2016-10-05 10:02
@lmr @ldoktor : anything can be done to make this work?

**Comment by ldoktor** [comment] 2016-10-06 09:55
OK, today I managed to reproduce it:

```
cd /tmp/aaa
/tmp/glibc/configure --prefix="/tmp/aaa"
make -j8
python
Python 2.7.11 (default, Sep  2 2016, 14:51:16) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import build
>>> a=build.run_make("/tmp/aaa", extra_args="check -j 8")
```

it prints several messages about missing `libgcc_s.so.1` and it hangs in `avocado.core.process` in `_fill_streams` in `self.stderr_thread.join()`. I'm trying to find whether the `read` blocks, or whether we don't get to the finish condition. But it seems to reproduce 100% cases (last week it always worked, which is kind of weird) so I should be able to find and fix the bug.

Next time ideally write avocado version (commit or release version), your system python version, how frequently this occurs and ideally simple reproducer (if available).

**Comment by PraveenPenguin** [comment] 2016-10-06 10:02
@ldoktor thanks a lot one question is this fix is available in avocado API ?

sorry next time we will provide all required info like  avocado version and python version

**Comment by ldoktor** [comment] 2016-10-06 10:21
Yep, so for some reason the stdout `os.read` finishes, but the stderr `os.read` does not. I'll play with the ways to solve this and let you know...

**Comment by PraveenPenguin** [comment] 2016-10-06 10:22
@ldoktor sure thanks

**Comment by ldoktor** [comment] 2016-10-06 11:03
OK, so right now I don't know why python returns `""` on `os.read` on `stdout`, but blocks on `stderr`. They are both handled the same way in our code and as @lmr pointed out it works fine in cpython.

Let me send a PR which uses `select` to check for new data, then we can try looking why is this behavior inconsistent.

**Comment by ldoktor** [comment] 2016-10-06 11:21
This takes care of the hang: https://github.com/avocado-framework/avocado/pull/1521 can you please verify it works for you as well?

**Comment by santhosh93** [comment] 2016-10-12 10:23
@ldoktor : Verified and it works fine after https://github.com/avocado-framework/avocado/pull/1521
Thanks for looking into the issue.

**Comment by ldoktor** [comment] 2016-10-14 10:55
@santhosh93 the use of `build.build(self.build_dir, extra_args='check', process_kwargs={"ignore_bg_processes": True, "ignore_status", True})` should serve your purpose. Note that you need the latest avocado in order for this to work, it's a new feature not backported to 36lts.

**Closed as completed by ldoktor** 2016-10-14 10:55 UTC
