### ISSUE TITLE
self.datadir variable is getting reset to None if the directory changed. 

### ISSUE THREAD

**Issue by santhosh93** [avocado-framework/avocado-misc-tests#9] opened 2016-04-21 15:42 UTC
```
 Debug Prints added in perf/stress.py 
```

->        print "Debug 1", self.datadir
           os.chdir(self.srcdir)
 ->       print "Debug 2", self.datadir
## Corresponding logs from job.log file:

2016-04-21 10:32:13,119 output           L0632 DEBUG| Debug 1 perf/stress.py.data
## 2016-04-21 10:32:13,119 output           L0632 DEBUG| Debug 2 None

It is seen that after changing the directory 'os.chdir(self.srcdir)' self.datadir getting  reset to None.

**Comment by ldoktor** [comment] 2016-04-21 16:09
Yep, I can reproduce it. The problem is that `inspect.getfile(self.__class__)` reports the relative path from the base location, but the location changes and the file does not exists anymore. It seems like we have to inspect the name better, or initialize it using abspath during `__init__`.

**Comment by ldoktor** [comment] 2016-04-21 16:14
Btw good think is it's (partially) fixed in python-3.4 :wink:. But I can see @sathanga choose the first approach, I'll take a look at it tomorrow.

**Comment by ldoktor** [comment] 2016-05-16 12:56
This should be resolved by https://github.com/avocado-framework/avocado/pull/1217

**Closed as completed** 2016-05-16 12:58 UTC
